# Generated by Django 4.1.7 on 2023-03-22 16:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_code', models.UUIDField(default=uuid.UUID('b5af43bf-075f-4944-8237-52231865f542'), unique=True)),
                ('protocol', models.CharField(max_length=10)),
                ('domain', models.CharField(max_length=32)),
                ('domain_zone', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=64)),
            ],
        ),
    ]
