# Generated by Django 4.1.7 on 2023-03-22 18:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0002_alter_link_link_code_alter_link_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_code',
            field=models.UUIDField(default=uuid.UUID('f3171931-ad51-40ea-9b04-4800b0e2467f'), unique=True),
        ),
    ]
