# Generated by Django 4.1.7 on 2023-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0004_alter_link_link_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='files')),
            ],
        ),
    ]
