# Generated by Django 4.1.7 on 2023-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_service", "0005_linkimport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link_code",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
