# Generated by Django 4.1.7 on 2023-08-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_service", "0006_alter_link_link_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="parameters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
