version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  migration:
    build: ..
    #        command: python3 manage.py migrate
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py migrate'

    depends_on:
      - db

  django_app:
    build: ..
    ports:
      - 8000:8000
    image: django_app:django_app
    container_name: django_project
    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - db
      - migration
